[package]
name = "rust-md5"
version = "0.1.0"
authors = ["Andre Lopes <andrelopesmds@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"

[lib]
name = "main"
crate-type = ["dylib"]